"""
Django settings for First Proj project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import environ
import os

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

print(f"BASE_DIR {BASE_DIR}")
print(f"VENV PATH: {os.path.join(BASE_DIR, '.env')}")
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b3oitn3ps5&oba0uy8n=lt39#nvr$zx36dijj-&%k7wo6tyhvo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*', 'pi-fd.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', # O Painel de Administracao
    'django.contrib.auth', # o app com funcionalidades de autenticacao
    'django.contrib.contenttypes', # O app com funcionalidades de relacoes dinamicas
    'django.contrib.sessions',     # O app para a administracao de sessoes HTTP
    'django.contrib.messages',     # O app para controle de mensagens SIMPLES
    'django.contrib.staticfiles',  # O app para trabalhar com arquivos estaticos (HTML, JAVA )
    'polls', # nosso app
    'polls_2',
]
# Classe que sao executadas no momento de processar uma request antes de executar um View
#
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'first_proj.urls'  # define qual sera o modulo urls.py principal do projeto

# simplesmente o sistema de Django
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# O modulo principal do WSGI
WSGI_APPLICATION = 'first_proj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# As configuracoes do banco de dados
DATABASES = {
    'default': env.db(),
}
""""
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        #Diz que tipo de banco de dados vc estara utilizando definindo o driver a utilizar
        # POSTGRES : psyocpg2
        #SQlite: sqlite3
        #SQLServer: pyodbc
        'NAME': '', # Nome do banco de dados
        'HOST': '', #A IP ou Dominio do servidor de banco de dados
        'PASSWORD':'', #A senha do banco de dados
        'USER': '', #O usuario do banco de dados

},
"""

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static file (CSS, Javascript, Images)
# https://docs.djangoproject.com/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static' # a pasta onde os arquivos estaticos estao

# A Classe que controla estes arquivos
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


#a pasta onde os arquivos staticos estao.

# A Classe que controla esses arquivos.
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"